version: '3.5'

services:
  alchemy_app:
    build: .
    image: alchemy_app:1.0.0
    depends_on:
      - db

  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alchemy_db
    ports:
      - "5432:5432"
    restart: always

  proxy:
    build: proxy
    image: afisha_proxy:1.0.0
    ports:
      - "8080:8080"