spring:
  profiles:
    active:
      - dev
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/alchemy_db
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: ilya.vatsevich@gmail.com
    password: tgnuotehjvlpnwct
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080

jwt_token:
  jwt_secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  jwt_issuer: IW
mail:
  activation_link: http://localhost:8080/api/v1/users/account_activation/

