spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_empty
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/alchemy_db
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: legenda5511@gmail.com
    password: vaixujnnrjnnupob
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    # tgnuotehjvlpnwct ilya.vatsevich@gmail.com
    # vaixujnnrjnnupob legenda5511@gmail.com
server:
  port: 8080

security-custom:
  jwt-token:
    jwt-secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    jwt-issuer: IW
    jwt-expiration: 7200000  # 2 hours
  refresh-token:
    expiration: 604800000 # 7 days
open_api:
  paths:
    user_path:
      /api/v1/user/**
    ingredient_path:
      /api/v1/ingredient/**
    action_path:
      /api/v1/action/**
    user_ingredient_path:
      /api/v1/user_ingredient/**
task_custom:
  execution:
    pool:
      core-size: 5
      max-size: 10
      queue-capacity: 25
    shutdown:
      await-termination: true
user_pattern:
  start-gold: 100
  is-active: true

