spring:
  profiles:
    active: @profileActive@
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/alchemy_db
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
server:
  port: 80
